Repository Gaurav-Verma07/sampark, pull requests merged in 2023-08, with the labels that each got.

#368 fix: solve all issue regarding to deployment
  app/blogs/[slug]/page.tsx
  app/blogs/page.tsx
  app/events/[slug]/page.tsx
  app/events/page.tsx
  app/impact/[slug]/page.tsx
  app/impact/page.tsx
  app/ngos/[slug]/page.tsx
  app/ngos/page.tsx
  app/orphanages/[slug]/page.tsx
  app/orphanages/page.tsx
  app/provider/page.tsx
  app/seeker/page.tsx
  server/index.ts
  server/src/blogs/blog.router.ts
  server/src/events/event.router.ts
  server/src/impact/impact.router.ts
  server/src/middleware/auth.middleware.ts
  server/src/ngos/ngo.router.ts
  server/src/orphnages/orphanage.router.ts
  server/src/users/user.router.ts
  server/src/users/user.service.ts
  src/components/Auth/Login.tsx
  src/components/Auth/Register.tsx
  src/components/Blogs/BlogCard.tsx
  src/components/Blogs/Blogs.tsx
  src/components/Blogs/SavedBlogs.tsx
  src/components/Events/EventsCard.tsx
  src/components/HomeHeader/HomeHeader.tsx
  src/utils/ApiRequests/firebaseGoogleAuth.ts
  src/utils/firebase.ts
Labels: gssoc23, level3

#374 feat: revamp the values section of homepage 🪄✨
  src/components/HomeOurValues/OurValues1.tsx
  src/components/HomeOurValues/Values.css
Labels: gssoc23, level2

#371 feat: create admin panel for blog page and data fetching for all blog page
  app/admin/page.tsx
  app/api/admin/blogs/getall/route.ts
  app/blogs/page.tsx
  src/components/Admin/Blog/AllBlogs.tsx
  src/components/Admin/Blog/BlogAdminCard.tsx
  src/components/Blogs/BlogCard.tsx
Labels: gssoc23, level3

#300 Auto assign feature added
  .github/workflows/issue-auto-assign.yml
Labels: gssoc23, level2

#381 feat: orphanage form create and update orphanage schema
  app/admin/orphanage/add/page.tsx
  app/admin/page.tsx
  server/schema/orphanage/OrphanagesSchema.ts
Labels: gssoc23, level3

#382 feat: add ngo form and update ngo schema
  app/admin/ngo/add/page.tsx
  server/schema/ngos/NgosSchema.ts
Labels: gssoc23, level3

#383 feat: event registration form add and update event schema
  app/admin/event/add/page.tsx
  server/schema/events/EventsSchema.ts
Labels: gssoc23, level3

#385 feat: add form add blog and update blog schema
  app/admin/blog/add/page.tsx
  server/schema/blogs/BlogsSchema.ts
Labels: gssoc23, level3

#387 chore: remove important data leaking console logs from codebase 🙅🏻🔥
  src/Pages/Seeker/index.tsx
  src/components/Auth/Login.tsx
  src/components/Auth/Register.tsx
  src/components/ContactUs/ContactUs.tsx
  src/components/ProviderCollegeTeam/ProviderCollegeTeam.tsx
  src/components/ProviderMain/ProviderMain.tsx
  src/utils/ApiRequests/firebaseAuth.ts
  src/utils/ApiRequests/userProfile.ts
Labels: gssoc23, level2

#388 fix: make side bar fully responsive for mobile devices 🪄✨
  src/components/MainHeader/styles.ts
Labels: gssoc23, level2

#395 feat: add orphanage create and update orphanage validation
  app/admin/orphanage/add/page.tsx
  app/api/admin/orphanage/add/route.ts
  server/src/orphnages/orphanage.interface.ts
  server/src/orphnages/orphanage.router.ts
  server/validationSchema/orphanageValidationSchema.ts
Labels: level3

#396 feat: add event data and update event validation
  app/admin/event/add/page.tsx
  app/api/admin/events/add/route.ts
  server/schema/events/EventsSchema.ts
  server/src/events/event.interface.ts
  server/src/events/event.router.ts
  server/validationSchema/eventValidationSchema.ts
Labels: gssoc23, level3

#397 feat: edit orphanage data
  app/admin/orphanage/edit/page.tsx
  app/api/admin/orphanage/edit/route.ts
  app/api/admin/orphanage/id/route.ts
  server/src/orphnages/orphanage.router.ts
Labels: gssoc23, level3

#398 feat: add edit functionality in event
  app/admin/event/edit/page.tsx
  app/api/admin/events/edit/route.ts
  app/api/admin/events/id/route.ts
  server/src/events/event.router.ts
Labels: gssoc23, level3

#407 feat: add deleteion feature for events
  app/admin/page.tsx
  app/api/admin/events/delete/route.ts
  server/src/events/event.router.ts
  src/components/Admin/Events/AllEvents.tsx
  src/components/Admin/Events/EventsAdminCard.tsx
Labels: gssoc23, level3

#408 feat: add deletetion feature for orphanage
  app/api/admin/orphanage/delete/route.ts
  server/src/orphnages/orphanage.service.ts
  src/components/Admin/Orphanages/AllOrphanages.tsx
  src/components/Admin/Orphanages/OrphangeAdminCard.tsx
Labels: gssoc23, level3

#416 feat: add edit a particular ngo feature
  app/admin/ngo/edit/page.tsx
  app/api/admin/ngos/edit/route.ts
  app/api/admin/ngos/id/route.ts
  server/src/ngos/ngo.router.ts
Labels: gssoc23, level3

#418 feat: create blog feature and update blog validation
  app/admin/blog/add/page.tsx
  app/api/admin/blogs/add/route.ts
  server/schema/blogs/BlogsSchema.ts
  server/src/blogs/blog.interface.ts
  server/src/blogs/blog.router.ts
  server/validationSchema/blogValidationSchema.ts
Labels: gssoc23, level3

#420 feat: add delete blog feature
  app/api/admin/blogs/delete/route.ts
  server/src/blogs/blog.service.ts
  src/components/Admin/Blog/AllBlogs.tsx
  src/components/Admin/Blog/BlogAdminCard.tsx
Labels: gssoc23, level3

#419 feat: add edit feature for blogs
  app/admin/blog/edit/page.tsx
  app/api/admin/blogs/edit/route.ts
  app/api/admin/blogs/id/route.ts
  server/src/blogs/blog.interface.ts
Labels: gssoc23, level3
