Repository Gaurav-Verma07/sampark, pull requests merged in 2023-06, with the labels that each got.

#76 made changes in the our values section
  package-lock.json
  src/components/HomeOurValues/OurValues1.tsx
  src/components/HomeOurValues/Values.css
Labels: gssoc23, level2

#99 Responsiveness added to page
  src/components/Blogs/Blogs.tsx
  src/components/HeroSection/styles.css
  src/components/HomeHeader/HomeHeader.tsx
  src/components/HomeHeader/styles.ts
  src/components/HomeOurValues/Values.css
  src/components/ImageGallery/ImageGallery.tsx
  src/components/ImageGallery/imagegallery.css
  src/components/MainBlogs/MainBlogs.tsx
  src/components/MainBlogs/blog.css
  src/components/MainHeader/styles.ts
  src/components/MapBox/MapBox.tsx
  src/components/MapBox/map.css
  src/components/Navbar/Navbar.tsx
  src/components/Navbar/styles.ts
Labels: gssoc23, level3

#98 Added good animation and CSS to cards
  src/components/HomeOurValues/Values.css
Labels: gssoc23, level3

#104 Create issue template for bug report
  .github/ISSUES_TEMPLATE/Bug_report.yml
Labels: gssoc23, level2

#110 Pull Request Template Added
  .github/Pull_Request_Template.md
Labels: gssoc23, level2

#112 Corrected typo in MapBox
  src/components/MapBox/MapBox.tsx
Labels: gssoc23, level1

#126 Contributing.md file added
  Contributing.md
Labels: gssoc23, level2

#121 Created Auto comment Feature.
  .github/ISSUE_TEMPLATE/bug.yml
  .github/workflows/auto-comment.yml
  src/utils/firebase.ts
  vercel.json
Labels: gssoc23, level2

#136 registration page updated
  src/components/Auth/Register.tsx
Labels: gssoc23, level2

#175 Create sitemap.xml
  public/sitemap.xml
Labels: gssoc23, level2

#177 Added linter
  .github/workflows/prettier.yml
Labels: gssoc23, level2

#189 Adding responsiveness on Register page
  src/components/Auth/Register.tsx
Labels: gssoc23, level1

#198 Meta tags added
  index.html
Labels: gssoc23, level2

#233 contact-inline-validation
  src/components/ContactUs/ContactUs.tsx
  src/utils/validation.ts
Labels: gssoc23, level2
