Repository Gaurav-Verma07/sampark, pull requests merged in 2023-07, with the labels that each got.

#257 feat: separate section with wishlisted blogs
  .github/ISSUE_TEMPLATE/bug.yml
  .github/workflows/close_old_issues.yaml
  .github/workflows/prettier.yml
  index.html
  package.json
  public/sitemap.xml
  src/App.tsx
  src/Pages/Error/index.css
  src/Pages/Error/index.tsx
  src/Pages/Home/index.tsx
  src/components/Auth/Login.tsx
  src/components/Auth/Register.tsx
  src/components/Blogs/AllBlogs.tsx
  src/components/Blogs/BlogCard.tsx
  src/components/Blogs/Blogs.tsx
  src/components/Blogs/SavedBlogs.tsx
  src/components/Blogs/blogContent.ts
  src/components/ContactUs/ContactUs.tsx
  src/components/Faq/Faq.tsx
  src/components/Faq/Faqstyles.css
  src/components/HomeHeader/HomeHeader.tsx
  src/components/HomeHeader/styles.ts
  src/components/MainBlogs/MainBlogs.tsx
  src/utils/firebase.ts
  src/utils/validation.ts
Labels: gssoc23, level3

#238 Add preloading Screen
  index.html
  package-lock.json
  src/App.css
  src/App.tsx
  src/Pages/Gallery/Gallery.tsx
  src/Pages/Gallery/gallery.css
  src/components/Auth/Register.tsx
  src/components/HomeOurValues/Values.css
  src/components/ImageGallery/ImageGallery.tsx
  style.css
Labels: gssoc23, level2

#226 #184 navbar fixed
  src/components/Navbar/Navbar.tsx
  src/components/Navbar/styles.ts
Labels: gssoc23, level1

#224 Removed the lines where firebase env variables where consoled/exposed
  src/components/Auth/Register.tsx
  src/utils/firebase.ts
Labels: gssoc23, level2

#210 Add logo of website in sign-in page
  package-lock.json
  package.json
  src/components/Auth/Login.tsx
Labels: gssoc23, level2

#265 feat: add server side validation
  server/index.ts
  server/package.json
  server/src/blogs/blog.router.ts
  server/src/events/event.router.ts
  server/src/ngos/ngo.router.ts
  server/src/orphnages/orphanage.router.ts
  server/src/users/user.router.ts
  server/validationSchema/blogValidationSchema.ts
  server/validationSchema/eventValidationSchema.ts
  server/validationSchema/ngoValidationSchema.ts
  server/validationSchema/orphanageValidationSchema.ts
  server/validationSchema/userValidationSchema.ts
Labels: gssoc23, level3

#262 Updated issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/documentation-issue.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: gssoc23, level2

#135 Fixed : issue #116
  package-lock.json
  package.json
  src/App.tsx
  src/components/GoToTopButton/GoToTop.css
  src/components/GoToTopButton/GoToTop.tsx
Labels: gssoc23, level1

#267 feat: auth middleware
  server/package.json
  server/src/blogs/blog.router.ts
  server/src/events/event.router.ts
  server/src/middleware/auth.middleware.ts
  server/src/ngos/ngo.router.ts
  server/src/orphnages/orphanage.router.ts
  server/src/users/user.router.ts
Labels: gssoc23, level3

#280 404 Error Page Fixed
  package-lock.json
  src/App.tsx
  src/Pages/Error/index.css
Labels: gssoc23, level2

#273 contact link fixed
  src/components/ContactUs/ContactUs.tsx
Labels: gssoc23, level1

#268 added impact section
  src/App.tsx
  src/assets/Images/NGO testimonial.jpeg
  src/assets/Images/impact1_riya.jpeg
  src/assets/Images/impact3_rahul.jpeg
  src/components/HomeHeader/HomeHeader.tsx
  src/components/Impact/AllImpacts.tsx
  src/components/Impact/Impact.tsx
  src/components/Impact/ImpactCard.tsx
  src/components/Impact/impact.css
  src/components/Impact/impactContent.ts
Labels: gssoc23, level3

#199 Lazy loading implemented
  package-lock.json
  package.json
  src/App.css
  src/App.tsx
Labels: gssoc23, level2

#305 feat:new faq added
  src/components/Faq/Faq.tsx
Labels: gssoc23, level3

#311 feat: add next image
  app/admin/page.tsx
  app/blogs/page.tsx
  app/gallery/page.tsx
  app/impact/page.tsx
  app/login/page.tsx
  app/page.tsx
  app/provider/page.tsx
  app/register/page.tsx
  app/seeker/page.tsx
  next.config.js
  public/assets/Images/NGO testimonial.jpeg
  public/assets/Images/homeImg.jpg
  public/assets/Images/impact1_riya.jpeg
  public/assets/Images/impact3_rahul.jpeg
  public/assets/Images/sampark_logo.svg
  public/assets/Images/samparklogotransparent.png
  public/assets/googleLogo.svg
  public/assets/react.svg
  src/components/Auth/Login.tsx
  src/components/Blogs/BlogCard.tsx
  src/components/Blogs/Blogs.tsx
  src/components/Blogs/blogContent.ts
  src/components/HomeHeader/HomeHeader.tsx
  src/components/ImageGallery/ImageGallery.tsx
  src/components/Impact/Impact.tsx
  src/components/Impact/ImpactCard.tsx
  src/components/Impact/impactContent.ts
  src/components/MainBlogs/MainBlogs.tsx
  src/components/MainBlogs/blogData.ts
Labels: gssoc23, level3

#308 feat: add navigation for next
  app/admin/page.tsx
  app/blogs/page.tsx
  app/gallery/page.tsx
  src/components/Auth/Login.tsx
  src/components/Auth/Register.tsx
  src/components/Blogs/BlogCard.tsx
  src/components/Blogs/Blogs.tsx
  src/components/Faq/Faq.tsx
  src/components/HomeHeader/HomeHeader.tsx
  src/components/ImageGallery/ImageGallery.tsx
  src/components/Impact/Impact.tsx
  src/components/Impact/ImpactCard.tsx
  src/components/MainBlogs/MainBlogs.tsx
  src/components/Navbar/Navbar.tsx
  src/components/SeekerNavbar/Navbar.tsx
Labels: gssoc23, level3

#314 fix: errors in pages
  app/admin/page.tsx
  app/blogs/page.tsx
  app/events/page.tsx
  app/gallery/galleryData.ts
  app/gallery/page.tsx
  app/impact/page.tsx
  app/login/page.tsx
  app/ngos/page.tsx
  app/orphanages/page.tsx
  app/page.tsx
  app/provider/page.tsx
  app/register/page.tsx
  app/seeker/page.tsx
  src/components/HomeHeader/HomeHeader.tsx
  tsconfig.node.json
  vite.config.ts
Labels: gssoc23, level3

#318 feat: routing for getstatic paths
  server/src/blogs/blog.router.ts
  server/src/blogs/blog.service.ts
  server/src/events/event.router.ts
  server/src/events/event.service.ts
  server/src/ngos/ngo.router.ts
  server/src/ngos/ngo.service.ts
  server/src/orphnages/orphanage.router.ts
  server/src/orphnages/orphanage.service.ts
Labels: gssoc23, level3

#330 feat: add ngo page
  app/globals.css
  app/ngos/ngo.css
  app/ngos/page.tsx
  src/components/Ngos/NgosCard.tsx
  src/components/Ngos/ngoContent.tsx
Labels: gssoc23, level3

#329 feat: add events page
  app/blogs/[id]/page.tsx
  app/blogs/page.tsx
  app/events/events.css
  app/events/page.tsx
  app/globals.css
  app/layout.tsx
  app/page.tsx
  src/components/Blogs/BlogCard.tsx
  src/components/Blogs/SavedBlogs.tsx
  src/components/Events/EventsCard.tsx
  src/components/Events/eventContent.ts
Labels: gssoc23, level3

#331 feat: add orphanage page
  app/globals.css
  app/orphanages/orphanage.css
  app/orphanages/page.tsx
  src/components/Orphanages/OrphanagesCard.tsx
  src/components/Orphanages/orphanageContent.ts
Labels: gssoc23, level3

#339 feat: add single event page
  app/events/[slug]/page.tsx
  server/schema/events/EventsSchema.ts
  server/src/events/event.router.ts
  server/validationSchema/eventValidationSchema.ts
Labels: gssoc23, level3

#340 feat: add single blog page
  app/blogs/[slug]/page.tsx
  server/schema/blogs/BlogsSchema.ts
  server/src/blogs/blog.router.ts
Labels: gssoc23, level3

#341 Feat: add single orphanage page
  app/orphanages/[slug]/page.tsx
  server/src/orphnages/orphanage.router.ts
Labels: gssoc23, level3

#342 feat: add single ngo page
  app/ngos/[slug]/page.tsx
  server/schema/ngos/NgosSchema.ts
  server/src/ngos/ngo.router.ts
Labels: gssoc23, level3

#344 feat: create database schema and backend validation for impact
  server/schema/impacts/ImpactsSchema.ts
  server/validationSchema/impactValidationSchema.ts
Labels: gssoc23, level3

#343 Feat: create routing and services for impact
  server/src/impact/impact.interface.ts
  server/src/impact/impact.router.ts
  server/src/impact/impact.service.ts
Labels: gssoc23, level3

#351 feat: user validation and database update
  server/schema/user/UserSchema.ts
  server/validationSchema/userValidationSchema.ts
Labels: gssoc23, level3

#352 feat: login signup feature
  package.json
  server/package-lock.json
  server/package.json
  src/components/Auth/Login.tsx
  src/components/Auth/Register.tsx
Labels: gssoc23, level3

#353 feat: user backend for login and signup
  server/index.ts
  server/src/users/user.interface.ts
  server/src/users/user.router.ts
  server/src/users/user.service.ts
Labels: gssoc23, level3

#354 Feat: add single impact page and updated impact schema
  app/impact/[slug]/page.tsx
  server/index.ts
  server/schema/impacts/ImpactSchema.ts
  server/src/impact/impact.router.ts
  server/src/impact/impact.service.ts
Labels: gssoc23, level3
